### ISSUE TITLE
 Proposal for Yatree Landing Page Redesign

### ISSUE THREAD

**Issue by AyushiTaralkar** [Mehtarishita/StationGuide#209]
The goal is to redesign the Yatree landing page to enhance its **visual appeal, improve user engagement, and elevate overall aesthetics.** The redesigned page will be **modern, attractive, and intuitive**, ensuring a seamless user experience. It will effectively communicate the platform's core value of connecting travelers with station services, ensuring ease of navigation and boosting user satisfaction.

**Comment by dhairyagothi** [comment]
how will you design ??

do you want to make figma design ??

**Comment by AyushiTaralkar** [comment]
Yes i will make a figma design first and in case u like it I can code it for you

**Comment by dhairyagothi** [comment]
that's great Ayushi @AyushiTaralkar  but i don't want to waste your valuable time , you make design i don't like it then it will be waste of your time . instead of creating complete new do changes in recent figma design then tell me i will definitely check and suggest changes and assign point for that .
here is figma design you copy this design and make changes and make a PR we will discuss there 

https://www.figma.com/design/EkIXVrH4wyDIE3oyJZpCkK/Station-Saarthi-(Copy)?t=eWAztD8YjXyHi6CV-1

good luck
